### ISSUE TITLE
[Bug] Crashes at launch on Android 14 Pixel 7 (GrapheneOS)

### ISSUE THREAD

**Issue by sebastien46** [nuclearfog/Apollo-Music#15]
```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023101300:user/release-keys
package: org.nuclearfog.apollo:28
process: org.nuclearfog.apollo:music
processUptime: 34285 + 357 ms
installer: com.machiav3lli.fdroid

java.lang.RuntimeException: Unable to create service org.nuclearfog.apollo.service.MusicPlaybackService: java.lang.SecurityException: org.nuclearfog.apollo: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4681)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2271)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: org.nuclearfog.apollo: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1873)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1801)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at org.nuclearfog.apollo.service.MusicPlaybackService.onCreate(SourceFile:277)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
	... 11 more

```

**Comment by nuclearfog** [comment]
fixed e9c7dd4ea95c150f0067c5b1b7387bb284f329f4
